version: 0.2

phases:
  pre_build:
    commands:
      - composer install -d app
      
  build:
    commands:
      - zip -r worker.zip ./app/worker/ ./app/vendor/ ./.ebextensions/ ./db.php ./cron.yaml

artifacts:
  files:
    - worker.zip